AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 40
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Style/Lambda:
  Enabled: false
